version: "3.8"

services:
  # MongoDB
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sparowapp
      MONGO_INITDB_ROOT_PASSWORD: sparrow123
    networks:
      - localnet

  # Api
  api:
    build:
      context: .
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./:/src
    networks:
      - localnet
    depends_on:
      - mongo
    env_file: ".env"

networks:
  localnet:
    driver: bridge
