name: Reusable Release Deploy
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'API version (v0, v1, v2, etc)'
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      KUBE_CONFIG:
        required: true
      RELEASE_NAMESPACE:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
          login-server: sparrowprod.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t sparrowprod.azurecr.io/release-api-${{ inputs.version }}:${{ github.run_number }}
          docker push sparrowprod.azurecr.io/release-api-${{ inputs.version }}:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: richardrigutins/replace-in-files@v1
        with:
          files: "./deploymentManifests/release-${{ inputs.version }}.yml"
          search-text: '_BUILD__ID_'
          replacement-text: '${{ github.run_number }}'

      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: ${{ secrets.RELEASE_NAMESPACE }}
          manifests: |
            ./deploymentManifests/release-${{ inputs.version }}.yml